env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'prettier'
rules: {
  "indent": [
    "error",
    2
  ],
  "prettier/prettier": [
    "error",
    {
      "printWidth": 120,
      "proseWrap": "never",
      "indent": ["error", 4],
    }
  ]
}
